[tool.poetry]
name = "bswitch_control"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
maturin = "^0.12.6"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "maturin"
