name: Release workflow
on:
  create:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - uses: actions-rs/cargo@v1
      with:
        command: install
        args: 'toml-cli'
    - run: |
        TEMP_FILE="$(mktemp)"
        VERSION=$(git describe --tags --abbrev=0)
        echo ${VERSION:1} > ./version
        cd python
        toml set Cargo.toml package.version ${VERSION:1} > "$TEMP_FILE"
        mv "$TEMP_FILE" Cargo.toml
      shell: bash
    - name: maturin-action
      uses: messense/maturin-action@v1
      with:
        maturin-version: latest
        command: sdist
        args: -m python/Cargo.toml
    - name: maturin-action
      uses: messense/maturin-action@v1
      with:
        maturin-version: latest
        command: build
        args: -m python/Cargo.toml
    - name: Archive Artifact
      uses: actions/upload-artifact@v2
      with:
        name: sdist
        path: ./target/wheels/
        if-no-files-found: error
    - name: Archive Version
      uses: actions/upload-artifact@v2
      with:
        name: version
        path: ./version
        if-no-files-found: error

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: version
    - id: get_version
      run: 'echo ::set-output "name=VERSION::$(cat ./version)"'
      shell: bash
    - name: Build Changelog
      id: github_release
      uses: mikepenz/release-changelog-builder-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: sdist
    - name: Upload release asset
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}
      with:
        body: |
          New release for ${{ github.sha }}.
          ${{ steps.github_release.outputs.changelog }}
        files: ./bswitch_python-*
